let
    //Query Fields List
    issuesFieldsList =
        {
            "id",
            "key",
            "summary",
            "description",
            "issuetype",
            "created",
            "components"
        },
    
    //Known Jira field schema definitions
    JiraKnownFields =
        #table
        (
            {"Name", "Type"}, 
            {
                {"id", type text},
                {"key", type text},
                {"self", type text},
                {"summary", type text},
                {"created", type datetimezone},
                {"updated", type datetimezone}
            }
        ),

    // Infer types from field names and value shape.
    // For custom fields without a "date" in the name, detect ISO 8601 datetime strings
    // by structure (YYYY-MM-DDTHH…) rather than by trying to parse the value — avoids
    // mis-typing text fields whose content happens to be parseable as a date.
    InferJiraFieldType = (fieldName as text, sampleValue as any) as type =>
        let
            lowerFieldName = Text.Lower(fieldName),
            typeFromName =
                if Text.StartsWith(lowerFieldName, "customfield_") then
                    if Text.Contains(lowerFieldName, "date") then type datetimezone
                    else type any
                else type any,
            // ISO 8601: positions 4, 7 = "-" and position 10 = "T"
            isIso8601Text =
                sampleValue is text and
                Text.Length(sampleValue) >= 20 and
                Text.At(sampleValue, 4)  = "-" and
                Text.At(sampleValue, 7)  = "-" and
                Text.At(sampleValue, 10) = "T",
            typeFromValue =
                if typeFromName <> type any then typeFromName
                else if isIso8601Text then type datetimezone
                else if sampleValue is text then type text
                else if sampleValue is number then type number
                else if sampleValue is list then type any
                else if sampleValue is record then type any
                else if sampleValue is table then type any
                else type any
        in
            typeFromValue,

    // Apply schema only to fields we can confidently type
    ApplyJiraSchema = (tbl as table) as table =>
        let
            tableColumns = Table.ColumnNames(tbl),
            sampleRow = if Table.RowCount(tbl) > 0 then tbl{0} else null,

            // Build schema for existing columns only
            schemaTransforms = List.Transform(tableColumns, (colName) =>
                let
                    knownTypeRow = Table.SelectRows(JiraKnownFields, each [Name] = colName),
                    knownType = if Table.RowCount(knownTypeRow) > 0 then 
                        knownTypeRow{0}[Type] else null,
                        
                    inferredType = if knownType = null and sampleRow <> null then
                        InferJiraFieldType(colName, Record.Field(sampleRow, colName))
                    else knownType,
                    
                    // Only transform if we have confidence in the type
                    finalType = if inferredType <> null and
                                    inferredType <> type any and
                                    inferredType <> type record and     // SKIP generic records
                                    inferredType <> type nullable record// SKIP nullable records
                                    then
                                    inferredType
                                else null
                in
                    if finalType <> null then {colName, finalType} else null
            ),
            
            // Remove null entries and apply transformations
            validTransforms = List.RemoveNulls(schemaTransforms),

            //original final step
            result = if List.Count(validTransforms) > 0 then
                Table.TransformColumnTypes(tbl, validTransforms)
            else tbl
        in
            result

in
    [
        issuesFieldsList = issuesFieldsList,
        JiraKnownFields = JiraKnownFields,
        InferJiraFieldType = InferJiraFieldType,
        ApplyJiraSchema = ApplyJiraSchema
    ]